nombre = input("Nombre: ")
apellido = input("Apellido: ")
rut = input("Rut: ")
duoc_mail = input("Duoc mail: ")
duoc_sede = input("Duoc sede: ")
print(f"Nombre: {nombre}, Apellido: {apellido}, Rut: {rut}, Duoc mail: {duoc_mail}, Duoc sede: {duoc_sede}")
